# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='Default Desc', max_length=255),
            preserve_default=False,
        ),
    ]
